comment:
        layout: header, changes, diff
coverage:
        status:
                project:
                        default:
                                target: auto
                patch:
                        default:
                                enabled: false
