---
version: '3.4'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
    deploy:
      replicas: 1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.2.3
    deploy:
      replicas: 1
    environment:
      LOG_LEVEL: debug
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline
      - ./facilities.json:/facilities.json.log

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.3
    deploy:
      replicas: 1
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - target: 5601
        published: 5601
        protocol: tcp
        mode: host

  redis:
    image: syncPool:latest
    deploy:
      replicas: 1

volumes:
  esdata:
    driver: local
